---
- name: "Playbook for provisioning the Packer Centos 8 Stream build"
  hosts: all
  become: true
  become_user: root

  tasks:  
    - name: upgrade all packages, excluding kernel
      dnf:
        name: "*"
        state: latest
        exclude: "kernel*"

    - name: Add the Vagrant user
      user:
        name: vagrant
        password: "{{ 'vagrant' | password_hash('sha512') }}"
        group: wheel

    - name: create sudoers file for the vagrant user
      file:
        path: /etc/sudoers.d/vagrant
        state: touch
        mode: '0440'

    - name:
      lineinfile:
        dest: /etc/sudoers.d/vagrant
        line: "vagrant ALL=(ALL) NOPASSWD:ALL"

    - name: Disable root Login over SSH
      lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^PermitRootLogin'
            line: "PermitRootLogin no"
            state: present
            backup: yes
      become: yes
      notify:
        - restart ssh

    - name: Change pw for root
      user:
        name: root
        update_password: always
        password: "{{ rootPassword | password_hash('md5') }}"

  handlers:
    - name: restart ssh
      systemd:
        name: sshd
        state: restarted