---
- name: "Playbook for provisioning the Packer Centos 8 Stream build"
  hosts: all
  become: true
  become_user: root
  
  tasks:
    - name: "debug message"
      debug:
        msg: "path >= dest"

# update all packages
#    - name: upgrade all packages
#      dnf:
#        name: "*"
#        state: latest


# create vagrant user + nopasswd
    - name: Add the Vagrant user
      user:
        name: vagrant
        password: "{{ 'vagrant' | password_hash('sha512') }}" # SECRET!
        group: wheel

    - name: create sudoers file for the vagrant user
      file:
        path: /etc/sudoers.d/vagrant
        state: touch
        mode: '0440'

    - name:
      lineinfile:
        dest: /etc/sudoers.d/vagrant
        line: "vagrant ALL=(ALL) NOPASSWD:ALL"

    # disable root login over ssh
    - name: Disable root Login
      lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^PermitRootLogin'
            line: "PermitRootLogin no"
            state: present
            backup: yes
      become: yes
      notify:
        - restart ssh

    - name: Change pw for root
      user:
        name: root
        update_password: always
        password: "{{ rootPassword | password_hash('md5') }}"

    # - name: change root pw with sh cmd
    #   expect:
    #     command: passwd -f root
    #     responses:
    #       (?i)password: "{{ rootPassword }}"
    #       (?i)password: "{{ rootPassword }}"          

    # Cleanup Vagrant home folder and /tmp

    #replace with file module
    # - name: Clean up vagrant homedir
    #   shell:
    #     cmd: /bin/rm -rf /home/vagrant/*

    # - name: Clean up /tmp
    #   shell:
    #     cmd: /bin/rm -rf /tmp/*

# Handlers
  handlers:
    - name: restart ssh
      systemd:
        name: sshd
        state: restarted