Vagrant.configure("2") do |config|                                                      # 2 =?

  config.vm.box         = "packer_centos-8-stream-builds_virtualbox"
  config.vm.box_url     = "file://../packer/packer_centos-8-stream-builds_virtualbox.box"   
  config.vm.box_version = ">=0"
  config.vm.guest       = "linux"
  config.vm.hostname    = "centos8stream"

  # config.vm.box_check_update = false                                                  # check for box updates on every "vagrant up"

  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"     # host only port forward 
  # config.vm.network "private_network", ip: "192.168.33.10"                            # host only network
  # config.vm.network "public_network"                                                  # bridged network

  config.vm.synced_folder ".", "/vagrant", disabled: false, automount: true             # Shared folder with host

  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant" #SECRET!

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "vagrant-centos8stream-vm"
    vb.gui    = false                                                                   # show VirtualBox remote terminal
    vb.cpus   = 2
    vb.memory = "4096"
  end

  # config.vm.provision "shell", inline: <<-SHELL                                       # box provisioning script(s)
  #   apt-get update
  # SHELL
end
